/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Comp;

import GUI.Main.Main;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicButtonListener;

/**
 *
 * @author quang
 */
public class PanelDashbroad extends javax.swing.JPanel {

    private int totalTable = 1;

    
    public PanelDashbroad() {
        initComponents();
        initReport();
    }

    public void initReport() {
        card1.setTitle("TỔNG BÀN");
        card1.setValue(10);
        
        card2.setTitle("ĐANG SỬ DỤNG");
        card2.setValue(4);
    }
    
    public void addTable() {
        TableBook table = new TableBook(totalTable++);
        table.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                jTextField1.setText(table.getNumberTable() + "");
            }
        });
        pnTableBook.add(table);
    }

    public void addTable(int totalTable) {
        int row = totalTable / 3;
        if (totalTable % 3 != 0) {
            row = (totalTable / 3) + 1;
        }
        int height = row * 125;
        pnTableBook.setPreferredSize(new Dimension(550, height));
        for (int i = 0; i < totalTable; i++) {
            addTable();
        }
    }

    public void setStatusTable(int numberTable, boolean rq) {
        Component[] listTable = pnTableBook.getComponents();
        for (Component x : listTable) {
            if (x instanceof TableBook) {
                if (((TableBook) x).getNumberTable() == numberTable) {
                    ((TableBook) x).setStatus(rq);
                }
            }
        }
    }
    
    public boolean isUsed(int numberTable) {
        Component[] listTable = pnTableBook.getComponents();
        for (Component x : listTable) {
            if (x instanceof TableBook) {
                if (((TableBook) x).getNumberTable() == numberTable) {
                    return ((TableBook) x).getStatus();
                }
            }
        }
        return false;
    }
    

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnTableBook = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnChuyenBan = new javax.swing.JButton();
        btnHuyBan = new javax.swing.JButton();
        btnKiemTra = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        btnDatBan = new javax.swing.JButton();
        card2 = new GUI.Comp.Card();
        card1 = new GUI.Comp.Card();

        setPreferredSize(new java.awt.Dimension(973, 666));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(550, 520));

        pnTableBook.setPreferredSize(new java.awt.Dimension(550, 510));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 12, 10);
        flowLayout1.setAlignOnBaseline(true);
        pnTableBook.setLayout(flowLayout1);
        jScrollPane2.setViewportView(pnTableBook);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thao tác", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(249, 340));

        btnChuyenBan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnChuyenBan.setText("CHUYỂN BÀN");

        btnHuyBan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHuyBan.setText("HUỶ BÀN");
        btnHuyBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBanActionPerformed(evt);
            }
        });

        btnKiemTra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnKiemTra.setText("KIỂM TRA");

        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThanhToan.setText("THANH TOÁN");

        btnDatBan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDatBan.setText("ĐẶT BÀN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKiemTra, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyBan, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChuyenBan, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnDatBan, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(btnChuyenBan, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(btnHuyBan, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(btnKiemTra, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(card1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(card2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(card1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(card2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBanActionPerformed
        if (jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jScrollPane2, "Chưa chọn bàn để huỷ");
            return;
        }
        int numberTable = Integer.parseInt(jTextField1.getText());
        if (!isUsed(numberTable)) {
            setStatusTable(numberTable, true);
            jTextField1.setText("");
        }
        else {
            JOptionPane.showMessageDialog(jScrollPane2, "Không thể huỷ bàn");
        }
        return;
    }//GEN-LAST:event_btnHuyBanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyenBan;
    public javax.swing.JButton btnDatBan;
    private javax.swing.JButton btnHuyBan;
    private javax.swing.JButton btnKiemTra;
    private javax.swing.JButton btnThanhToan;
    private GUI.Comp.Card card1;
    private GUI.Comp.Card card2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnTableBook;
    // End of variables declaration//GEN-END:variables
}
