package GUI.Comp;

import BUS.IngredientsBUS;
import DTO.IngredientsDTO;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Tai
 */
public class QuanLiNguyenLieu extends javax.swing.JPanel {

    /**
     * Creates new form QuanLiNguyenLieu
     */
    public QuanLiNguyenLieu() throws Exception {
        initComponents();
        loadDataToTable(jTable1);
        jTextField1.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập tên nguyên liệu");

    }

    private void loadDataToTable(JTable table) throws Exception {
        // Tạo một đối tượng IngredientsBUS
        IngredientsBUS ingredientsBUS = new IngredientsBUS();

        // Gọi phương thức để lấy danh sách nguyên liệu từ cơ sở dữ liệu
        ArrayList<IngredientsDTO> ingredientsList = ingredientsBUS.getAllActiveIngredients();

        // Tạo DefaultTableModel để đặt dữ liệu vào jTable
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        // Xóa toàn bộ dữ liệu cũ trong jTable
        model.setRowCount(0);

        // Duyệt qua danh sách nguyên liệu và thêm từng dòng vào jTable
        for (IngredientsDTO ingredient : ingredientsList) {
            Object[] row = {false, ingredient.getId(), ingredient.getName(), ingredient.getDes(), ingredient.getQuantity(), ingredient.getUnit()};
            model.addRow(row);
        }
        // Lấy đối tượng header của JTable
        TableColumnModel columnModel = jTable1.getColumnModel();

// Lặp qua từng cột trong JTable
        for (int columnIndex = 0; columnIndex < jTable1.getColumnCount(); columnIndex++) {
            // Lấy renderer của header của từng cột
            DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer();

            // Đặt căn lề trái cho renderer của header
            headerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.LEFT);

            // Lấy đối tượng cột trong cấu hình cột của JTable
            columnModel.getColumn(columnIndex).setHeaderRenderer(headerRenderer);
        }
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(JLabel.LEFT);
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }

        columnModel.getColumn(0).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JCheckBox checkBox = new JCheckBox();
                checkBox.setSelected((boolean) value);
                checkBox.setHorizontalAlignment(JLabel.LEFT);
                checkBox.setBackground(new Color(35, 35, 35));

                return checkBox;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        panelBackground1 = new GUI.Comp.Swing.PanelBackground();
        panelBackground2 = new GUI.Comp.Swing.PanelBackground();
        panelBackground3 = new GUI.Comp.Swing.PanelBackground();
        panelBackground4 = new GUI.Comp.Swing.PanelBackground();
        panelBackground5 = new GUI.Comp.Swing.PanelBackground();
        panelBackground6 = new GUI.Comp.Swing.PanelBackground();
        panelBackground7 = new GUI.Comp.Swing.PanelBackground();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        panelBackground8 = new GUI.Comp.Swing.PanelBackground();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel3.setMaximumSize(new java.awt.Dimension(50, 23));
        jPanel3.setPreferredSize(new java.awt.Dimension(50, 23));

        setBackground(new java.awt.Color(30, 30, 30));
        setLayout(new java.awt.BorderLayout());

        panelBackground1.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground1.setLayout(new java.awt.BorderLayout());

        panelBackground2.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground1.add(panelBackground2, java.awt.BorderLayout.LINE_START);

        panelBackground3.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground3.setPreferredSize(new java.awt.Dimension(10, 20));
        panelBackground1.add(panelBackground3, java.awt.BorderLayout.PAGE_START);

        panelBackground4.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground4.setToolTipText("");
        panelBackground1.add(panelBackground4, java.awt.BorderLayout.LINE_END);

        panelBackground5.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground1.add(panelBackground5, java.awt.BorderLayout.PAGE_END);

        panelBackground6.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground6.setLayout(new java.awt.BorderLayout(0, 25));

        panelBackground7.setBackground(new java.awt.Color(35, 35, 35));
        panelBackground7.setMinimumSize(new java.awt.Dimension(1000, 23));
        panelBackground7.setPreferredSize(new java.awt.Dimension(1000, 60));
        panelBackground7.setLayout(new javax.swing.BoxLayout(panelBackground7, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(35, 35, 35));
        jPanel2.setMaximumSize(new java.awt.Dimension(50, 23));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 23));
        panelBackground7.add(jPanel2);

        jButton1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton1.setText("Thêm");
        jButton1.setMaximumSize(new java.awt.Dimension(72, 40));
        panelBackground7.add(jButton1);

        jPanel4.setBackground(new java.awt.Color(35, 35, 35));
        jPanel4.setMaximumSize(new java.awt.Dimension(50, 23));
        jPanel4.setPreferredSize(new java.awt.Dimension(50, 23));
        panelBackground7.add(jPanel4);

        jButton3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton3.setText("Sửa");
        jButton3.setMaximumSize(new java.awt.Dimension(72, 40));
        panelBackground7.add(jButton3);

        jPanel5.setBackground(new java.awt.Color(35, 35, 35));
        jPanel5.setMaximumSize(new java.awt.Dimension(50, 23));
        jPanel5.setPreferredSize(new java.awt.Dimension(50, 23));
        panelBackground7.add(jPanel5);

        jButton4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton4.setText("Xóa");
        jButton4.setMaximumSize(new java.awt.Dimension(72, 40));
        panelBackground7.add(jButton4);

        jPanel6.setBackground(new java.awt.Color(35, 35, 35));
        jPanel6.setMaximumSize(new java.awt.Dimension(50, 23));
        jPanel6.setPreferredSize(new java.awt.Dimension(50, 23));
        panelBackground7.add(jPanel6);

        jLabel1.setText("Tìm kiếm");
        panelBackground7.add(jLabel1);

        jPanel1.setBackground(new java.awt.Color(35, 35, 35));
        jPanel1.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanel1.setPreferredSize(new java.awt.Dimension(20, 20));
        panelBackground7.add(jPanel1);

        jTextField1.setMaximumSize(new java.awt.Dimension(175, 30));
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 50));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        panelBackground7.add(jTextField1);

        panelBackground6.add(panelBackground7, java.awt.BorderLayout.PAGE_START);

        panelBackground8.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground8.setLayout(new java.awt.BorderLayout());

        jTable1.setBackground(new java.awt.Color(35, 35, 35));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "ID", "Tên", "Mô Tả", "Số lượng", "đơn vị"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(25);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(25);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(25);
        }

        panelBackground8.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelBackground6.add(panelBackground8, java.awt.BorderLayout.CENTER);

        panelBackground1.add(panelBackground6, java.awt.BorderLayout.CENTER);

        add(panelBackground1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // Lấy dữ liệu nhập vào từ ô text field
        String searchText = jTextField1.getText().trim();

        // Kiểm tra xem có dữ liệu nhập vào không
        if (!searchText.isEmpty()) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int rowCount = model.getRowCount();
            boolean found = false;

            // Duyệt qua các dòng trong jTable để tìm kiếm dữ liệu phù hợp
            for (int i = 0; i < rowCount; i++) {
                String name = (String) model.getValueAt(i, 2); // Lấy tên nguyên liệu từ cột thứ 3 (index 2)

                // Nếu tên nguyên liệu chứa chuỗi tìm kiếm thì hiển thị dòng đó
                if (name.toLowerCase().contains(searchText.toLowerCase())) {
                    jTable1.getSelectionModel().setSelectionInterval(i, i); // Chọn dòng tìm thấy
                    jTable1.scrollRectToVisible(jTable1.getCellRect(i, 0, true)); // Cuộn đến dòng được chọn
                    found = true;
                    break;
                }
            }

            // Nếu không tìm thấy dữ liệu phù hợp, hiển thị thông báo
            if (!found) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu phù hợp.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JTextField jTextField1;
    public GUI.Comp.Swing.PanelBackground panelBackground1;
    public GUI.Comp.Swing.PanelBackground panelBackground2;
    public GUI.Comp.Swing.PanelBackground panelBackground3;
    public GUI.Comp.Swing.PanelBackground panelBackground4;
    public GUI.Comp.Swing.PanelBackground panelBackground5;
    public GUI.Comp.Swing.PanelBackground panelBackground6;
    public GUI.Comp.Swing.PanelBackground panelBackground7;
    public GUI.Comp.Swing.PanelBackground panelBackground8;
    // End of variables declaration//GEN-END:variables
}
