/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Comp;

import BUS.RecipesBUS;
import DTO.RecipesDTO;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tai
 */
public class QuanLiMonAn extends javax.swing.JPanel {

    /**
     * Creates new form QuanLiMonAn
     */
    public QuanLiMonAn() {
        initComponents();
        loadDataToTable();

    }

    // Method to load data from tb_recipes to JTable
    private void loadDataToTable() {
        RecipesBUS recipesBUS = new RecipesBUS(); // Tạo một thể hiện của lớp RecipesBUS
        ArrayList<RecipesDTO> listRecipes = recipesBUS.getAllData();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0); // Clear existing rows
        Object[] row = new Object[2]; // Assuming there are two columns: ID and Name
        for (RecipesDTO recipe : listRecipes) {
            row[0] = recipe.getId();
            row[1] = recipe.getName();
            model.addRow(row);
        }
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < jTable2.getColumnCount(); i++) {
            jTable2.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground1 = new GUI.Comp.Swing.PanelBackground();
        panelBackground2 = new GUI.Comp.Swing.PanelBackground();
        panelBackground3 = new GUI.Comp.Swing.PanelBackground();
        panelBackground4 = new GUI.Comp.Swing.PanelBackground();
        panelBackground5 = new GUI.Comp.Swing.PanelBackground();
        panelBackground6 = new GUI.Comp.Swing.PanelBackground();
        panelBackground7 = new GUI.Comp.Swing.PanelBackground();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        panelBackground8 = new GUI.Comp.Swing.PanelBackground();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setBackground(new java.awt.Color(30, 30, 30));
        setLayout(new java.awt.BorderLayout());

        panelBackground1.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground1.setLayout(new java.awt.BorderLayout());

        panelBackground2.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground2.setPreferredSize(new java.awt.Dimension(100, 20));
        panelBackground1.add(panelBackground2, java.awt.BorderLayout.PAGE_START);

        panelBackground3.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground3.setPreferredSize(new java.awt.Dimension(20, 100));
        panelBackground1.add(panelBackground3, java.awt.BorderLayout.LINE_START);

        panelBackground4.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground4.setPreferredSize(new java.awt.Dimension(20, 100));
        panelBackground1.add(panelBackground4, java.awt.BorderLayout.LINE_END);

        panelBackground5.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground5.setPreferredSize(new java.awt.Dimension(100, 20));
        panelBackground1.add(panelBackground5, java.awt.BorderLayout.PAGE_END);

        panelBackground6.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground6.setForeground(new java.awt.Color(255, 204, 102));
        panelBackground6.setLayout(new java.awt.BorderLayout(0, 25));

        panelBackground7.setBackground(new java.awt.Color(35, 35, 35));
        panelBackground7.setPreferredSize(new java.awt.Dimension(100, 50));
        panelBackground7.setLayout(new javax.swing.BoxLayout(panelBackground7, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(35, 35, 35));
        jPanel1.setMaximumSize(new java.awt.Dimension(50, 23));
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 23));
        panelBackground7.add(jPanel1);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 53, 53)));
        jButton1.setMaximumSize(new java.awt.Dimension(72, 40));
        jButton1.setPreferredSize(new java.awt.Dimension(72, 72));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelBackground7.add(jButton1);

        jPanel3.setBackground(new java.awt.Color(35, 35, 35));
        jPanel3.setMaximumSize(new java.awt.Dimension(50, 23));
        jPanel3.setPreferredSize(new java.awt.Dimension(50, 23));
        panelBackground7.add(jPanel3);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sửa");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 53, 53)));
        jButton2.setMaximumSize(new java.awt.Dimension(72, 40));
        jButton2.setPreferredSize(new java.awt.Dimension(72, 72));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelBackground7.add(jButton2);

        jPanel2.setBackground(new java.awt.Color(35, 35, 35));
        jPanel2.setMaximumSize(new java.awt.Dimension(50, 23));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 23));
        panelBackground7.add(jPanel2);

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Xóa");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 53, 53)));
        jButton3.setMaximumSize(new java.awt.Dimension(72, 40));
        jButton3.setPreferredSize(new java.awt.Dimension(72, 72));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelBackground7.add(jButton3);

        panelBackground6.add(panelBackground7, java.awt.BorderLayout.PAGE_START);

        panelBackground8.setBackground(new java.awt.Color(35, 35, 35));
        panelBackground8.setLayout(new java.awt.BorderLayout());

        jTable2.setBackground(new java.awt.Color(35, 35, 35));
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Tên"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTable2ComponentResized(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        panelBackground8.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        panelBackground6.add(panelBackground8, java.awt.BorderLayout.CENTER);

        panelBackground1.add(panelBackground6, java.awt.BorderLayout.CENTER);

        add(panelBackground1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable2ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2ComponentResized

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Hiển thị các hộp thoại để yêu cầu nhập thông tin
        String idInput = JOptionPane.showInputDialog(this, "Nhập ID:");
        if (idInput == null || idInput.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID không được để trống.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return; // ID không được để trống
        }
        int id;
        try {
            id = Integer.parseInt(idInput);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID phải là một số nguyên.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return; // ID không hợp lệ
        }

        String name = JOptionPane.showInputDialog(this, "Nhập tên món ăn:");
        if (name == null || name.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên món ăn không được để trống.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return; // Tên món ăn không được để trống
        }

        // Thử thêm món ăn và xử lý ngoại lệ nếu có
        RecipesBUS recipesBUS = new RecipesBUS();
        try {
            recipesBUS.insertData(id, name);
            // Nếu không có lỗi, cập nhật dữ liệu trên JTable
            loadDataToTable();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Thêm món ăn thất bại. Vui lòng thử lại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Kiểm tra xem người dùng đã chọn một dòng để xóa hay chưa
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return; // Không có dòng nào được chọn, thoát khỏi phương thức
        }

        // Hiển thị hộp thoại xác nhận
        int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa dòng này không?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);

        // Nếu người dùng chọn "Yes" (option = 0), thực hiện xóa
        if (option == JOptionPane.YES_OPTION) {
            // Lấy giá trị của ID từ cột đầu tiên trong dòng đã chọn
            int id = (int) jTable2.getValueAt(selectedRow, 0);

            // Gọi phương thức deleteData() từ RecipesBUS để xóa dòng dữ liệu khỏi tb_recipes
            RecipesBUS recipesBUS = new RecipesBUS();
            recipesBUS.deleteData(id);

            // Cập nhật lại dữ liệu trên JTable
            loadDataToTable();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Kiểm tra xem người dùng đã chọn một dòng để sửa hay không
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để sửa.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return; // Không có dòng nào được chọn, thoát khỏi phương thức
        }

        // Lấy thông tin hiện tại của dòng đã chọn
        int id = (int) jTable2.getValueAt(selectedRow, 0);
        String currentName = (String) jTable2.getValueAt(selectedRow, 1);

        // Hiển thị hộp thoại cho phép người dùng nhập thông tin mới
        String newName = JOptionPane.showInputDialog(this, "Nhập tên mới cho món ăn:", currentName);
        if (newName == null || newName.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên món ăn không được để trống.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return; // Tên món ăn không được để trống
        }

        // Gọi phương thức updateData() từ RecipesBUS để cập nhật thông tin mới
        RecipesBUS recipesBUS = new RecipesBUS();
        recipesBUS.updateData(id, newName);

        // Cập nhật lại dữ liệu trên JTable
        loadDataToTable();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable2;
    public GUI.Comp.Swing.PanelBackground panelBackground1;
    public GUI.Comp.Swing.PanelBackground panelBackground2;
    public GUI.Comp.Swing.PanelBackground panelBackground3;
    public GUI.Comp.Swing.PanelBackground panelBackground4;
    public GUI.Comp.Swing.PanelBackground panelBackground5;
    public GUI.Comp.Swing.PanelBackground panelBackground6;
    public GUI.Comp.Swing.PanelBackground panelBackground7;
    public GUI.Comp.Swing.PanelBackground panelBackground8;
    // End of variables declaration//GEN-END:variables
}
